### ISSUE TITLE
When will open source

### ISSUE THREAD

**Issue by Frank-Star-fn** [colorfulfuture/GC-VRNN#1]
Hello author, your work is very good, and I would like to reproduce your work. May I ask when the code will be open source?

**Comment by colorfulfuture** [comment]
Hi, 

Thank you for your interest in our work. Could you tell me your Email or WeChat? I can send you the unofficial version code of our work (because I haven't heard from the company side for a long time).

Best,
Yi

**Comment by colorfulfuture** [comment]
Sent!
